version: 0.0
os: linux
files:
 - source: /home/ubuntu/portfolio-design
   destination: /var/www/html/portfolio-design
 - source: /home/ubuntu/portfolio-design/index.html
   destination: /var/www/html/index.html
